version: "3"
services:

  teslalogger:
    image: mono:6.0.0.313
    volumes:
      - ./TeslaLogger/bin/:/etc/teslalogger
    working_dir: /etc/teslalogger
    command: [ mono, /etc/teslalogger/TeslaLogger.exe ]
    depends_on:
      - database
  
  database:
    image: mariadb:10.4.7
    env_file:
      - .env
    volumes:
      - ./TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
      - teslalogger-database:/var/lib/mysql
    ports: 
      - 3306:3306
        
  grafana:
    image: grafana/grafana:6.3.2
    environment:
      - GF_DATABASE_USER=${MYSQL_USER}
      - GF_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - GF_DATABASE_NAME=${MYSQL_DATABASE}
      - GF_DATABASE_HOST=database:3306
      - GF_DATABASE_TYPE=mysql
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
    ports: 
      - 3000:3000
    volumes: 
      - teslalogger-grafana:/var/lib/grafana
    depends_on:
      - teslalogger

  webserver:
    image: php:7.3-apache
    volumes:
      - ./TeslaLogger/www:/var/www/html
      - ./TeslaLogger/bin/:/etc/teslalogger
    ports:
      - 80:80
            
volumes:
    teslalogger-grafana:
    teslalogger-database: